export const LOAD_POSTS_START = "LOAD_POSTS_START";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_ERROR = "LOAD_POSTS_ERROR";
export const ADD_POST = "ADD_POST";

export const CREATE_POSTS_START = "CREATE_POSTS_START";
export const CREATE_POSTS_SUCCESS = "CREATE_POSTS_SUCCESS";
export const CREATE_POSTS_ERROR = "CREATE_POSTS_ERROR";

export const DELETE_POSTS_START = "DELETE_POSTS_START";
export const DELETE_POSTS_SUCCESS = "DELETE_POSTS_SUCCESS";
export const DELETE_POSTS_ERROR = "DELETE_POSTS_ERROR";
export const DELETE_POST = "DELETE_POST";

export const UPDATE_POSTS_START = "UPDATE_POSTS_START";
export const UPDATE_POSTS_SUCCESS = "UPDATE_POSTS_SUCCESS";
export const UPDATE_POSTS_ERROR = "UPDATE_POSTS_ERROR";
export const UPDATE_POST = "UPDATE_POST";

export const POST_HISTORY_START = "POST_HISTORY_START";
export const POST_HISTORY_SUCCESS = "POST_HISTORY_SUCCESS";
